# Generated by Django 5.1.1 on 2025-06-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open', models.IntegerField()),
                ('High', models.IntegerField()),
                ('Low', models.IntegerField()),
                ('PrevClose', models.IntegerField()),
            ],
            options={
                'db_table': 'Prices',
            },
        ),
    ]
